//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSMVCFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSDBFinalEntities : DbContext
    {
        public CMSDBFinalEntities()
            : base("name=CMSDBFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Post> tbl_Post { get; set; }
        public DbSet<tbl_Retrieve> tbl_Retrieve { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
    }
}
